services:
  web:
    image: ghcr.io/codemasterdevops421/srignanodaya-website:main
    container_name: srignanodaya-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - school-net

networks:
  school-net:
    driver: bridge
